use std::borrow::Cow;

pub fn zh_cn(text: &str) -> Option<&'static str> {
    zh_cn_static(text)
}

pub fn localize(text: &str) -> Cow<'_, str> {
    zh_cn(text).map_or(Cow::Borrowed(text), Cow::Borrowed)
}

fn zh_cn_static(text: &str) -> Option<&'static str> {
    match text {
        "Account" => Some("账户"),
        "Agents" => Some("智能体"),
        "Billing and usage" => Some("账单和用量"),
        "Code" => Some("代码"),
        "Cloud platform" => Some("云平台"),
        "Teams" => Some("团队"),
        "Appearance" => Some("外观"),
        "Features" => Some("功能"),
        "Keyboard shortcuts" => Some("键盘快捷键"),
        "Warpify" => Some("Warpify"),
        "Referrals" => Some("推荐"),
        "Shared blocks" => Some("共享块"),
        "Warp Drive" => Some("Warp Drive"),
        "Privacy" => Some("隐私"),
        "About" => Some("关于"),
        "Warp Agent" => Some("Warp 智能体"),
        "Profiles" => Some("配置文件"),
        "MCP servers" => Some("MCP 服务器"),
        "Knowledge" => Some("知识库"),
        "Third party CLI agents" => Some("第三方 CLI 智能体"),
        "Indexing and projects" => Some("索引和项目"),
        "Editor and Code Review" => Some("编辑器和代码审查"),
        "Environments" => Some("环境"),
        "Oz Cloud API Keys" => Some("Oz Cloud API 密钥"),
        "MCP Servers" => Some("MCP 服务器"),
        "Preferences" => Some("偏好设置"),
        "Privacy Policy..." => Some("隐私政策..."),
        "Debug" => Some("调试"),
        "Set Warp as Default Terminal" => Some("将 Warp 设为默认终端"),
        "Log out" => Some("退出登录"),
        "Open Recent" => Some("打开最近项目"),
        "Use Warp's Prompt" => Some("使用 Warp 提示符"),
        "Copy on Select within the Terminal" => Some("在终端中选择即复制"),
        "Synchronize Inputs" => Some("同步输入"),
        "Toggle Mouse Reporting" => Some("切换鼠标报告"),
        "Toggle Scroll Reporting" => Some("切换滚动报告"),
        "Toggle Focus Reporting" => Some("切换焦点报告"),
        "Compact Mode" => Some("紧凑模式"),
        "Send Feedback..." => Some("发送反馈..."),
        "Warp Documentation..." => Some("Warp 文档..."),
        "GitHub Issues..." => Some("GitHub Issues..."),
        "Warp Slack Community..." => Some("Warp Slack 社区..."),
        "Save New..." => Some("另存为新配置..."),
        "New Window" => Some("新建窗口"),
        "New Terminal Tab" => Some("新建终端标签页"),
        "New Agent Tab" => Some("新建智能体标签页"),
        "Reopen closed session" => Some("重新打开已关闭会话"),
        "Launch Configurations" => Some("启动配置"),
        "Enable Shell Debug Mode (-x) for New Sessions" => Some("为新会话启用 Shell 调试模式 (-x)"),
        "Disable Shell Debug Mode (-x) for New Sessions" => Some("为新会话停用 Shell 调试模式 (-x)"),
        "Enable In-band Generators for New Sessions" => Some("为新会话启用内联生成器"),
        "Disable in-band generators for new sessions" => Some("为新会话停用内联生成器"),
        "Enable PTY Recording Mode (warp.pty.recording)" => {
            Some("启用 PTY 录制模式 (warp.pty.recording)")
        },
        "Disable PTY Recording Mode (warp.pty.recording)" => {
            Some("停用 PTY 录制模式 (warp.pty.recording)")
        },
        "Show Initialization Block" => Some("显示初始化块"),
        "Hide Initialization Block" => Some("隐藏初始化块"),
        "Show In-band Command Blocks" => Some("显示内联命令块"),
        "Hide In-band Command Blocks" => Some("隐藏内联命令块"),
        "Show Warpified SSH Blocks" => Some("显示 Warpified SSH 块"),
        "Hide Warpified SSH Blocks" => Some("隐藏 Warpified SSH 块"),
        "Manually Toggle Network Status" => Some("手动切换网络状态"),
        "Export Default Settings as CSV to home dir" => Some("将默认设置导出为 CSV 到主目录"),
        "Create anonymous user" => Some("创建匿名用户"),
        "Open Settings" => Some("打开设置"),
        "Settings" => Some("设置"),
        "Appearance..." => Some("外观..."),
        "About Warp" => Some("关于 Warp"),
        "Open Team Settings" => Some("打开团队设置"),
        "Configure Keyboard Shortcuts..." => Some("配置键盘快捷键..."),
        "Open Repository" => Some("打开仓库"),
        "Project Explorer" => Some("项目资源管理器"),
        "Global Search" => Some("全局搜索"),
        "Command Palette" => Some("命令面板"),
        "Navigation Palette" => Some("导航面板"),
        "Reset to default" => Some("重置为默认值"),
        "General" => Some("通用"),
        "Theme" => Some("主题"),
        "Font" => Some("字体"),
        "Terminal" => Some("终端"),
        "Input" => Some("输入"),
        "Text" => Some("文本"),
        "Cursor" => Some("光标"),
        "Notifications" => Some("通知"),
        "Startup" => Some("启动"),
        "Updates" => Some("更新"),
        "Security" => Some("安全"),
        "Advanced" => Some("高级"),
        "Keyboard Shortcuts" => Some("键盘快捷键"),
        "AI Settings" => Some("AI 设置"),
        "File" => Some("文件"),
        "Edit" => Some("编辑"),
        "View" => Some("视图"),
        "Tab" => Some("标签页"),
        "AI" => Some("AI"),
        "Blocks" => Some("块"),
        "Drive" => Some("Drive"),
        "Window" => Some("窗口"),
        "Help" => Some("帮助"),
        _ => None,
    }
}

#[cfg(test)]
#[path = "localization_tests.rs"]
mod tests;
